import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Footer, Header } from "./_components"
import { HeaderContextProvider } from "./_hooks"
import { Menu } from "./_components/menu"
import { ContentWrapper } from "./_components/content-wrapper"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <HeaderContextProvider>
          <Menu />
          <Header />
          <ContentWrapper>
            <>{children}</>
            <Footer />
          </ContentWrapper>
        </HeaderContextProvider>
      </body>
    </html>
  )
}
